//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class favourite
    {
        public int fid { get; set; }
        public string Email { get; set; }
        public string CityName { get; set; }
        public string Zipcode { get; set; }
    
        public virtual register register { get; set; }
    }
}
